name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  FORCE_COLOR: "1"

jobs:
  release:
    environment: pypi
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          python-version: 3.12

      - name: Install nox
        run: |
          uv pip install nox
          nox --version

      - name: Build package
        run: nox -s build-3.12

      - name: Upload package
        if: github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@release/v1
